### ISSUE TITLE
Dry run option?

### ISSUE THREAD

**Issue by danawoodman** [jalkoby/squasher#13]
Is there any way to do a "dry run"? Eg, simulate what would happen locally? I working with a really old and long migration history and getting lots of exceptions (not squasher related) and I'd like to simulate things rather than files being deleted and me having to revert them.

Semi-related: would be great to also have an option for not wiping the existing squasher DB so I can do the migration in stages without seed data getting wiped.

Thanks!

**Comment by jalkoby** [comment]
For that moment there is no "dry run" option. For that case you can use your control version software to revert all changes by squasher.

About the second - well it's sounds like a good idea. Need to think about it a little bit more

**Comment by jalkoby** [comment]
Release 0.2.0 adds both features - "dry" mode with "-d" option, "reuse database" - "-r" option

**Comment by danawoodman** [comment]
Awesome thanks @jalkoby
