### ISSUE TITLE
null false option for booleans

### ISSUE THREAD

**Issue by mmplisskin** [jalkoby/squasher#19]
In a previous migration I had specified nil:false to avoid the three state boolean:

`t.boolean :scheduled, default: false, nil: false`

When using squasher nil:false is not specified:

`t.boolean  "scheduled",                              default: false`

**Comment by jalkoby** [comment]
The option "nil: false" is invalid for rails migration dsl. The correct one is "null: false", so squasher didn't change anything, just clean a useless parameter

**Comment by mmplisskin** [comment]
Very Sorry, Thank you. Should have noticed this it was late at night.
