### ISSUE TITLE
Squashing mechanism is not verbatim

### ISSUE THREAD

**Issue by vemv** [jalkoby/squasher#23]
Squasher's current squashing implementation is pretty but flawed, as I see it.

My original migrations contain conditionals and loops. After all, migrations are arbitrary Ruby code, not plain dumb data.

After the squash, all custom ruby code disappeared, being replaced by the resulting `create_table` statements.

That's quite an anti-feature, especially for applications that can be parameterized with various configuration (like `ENV`).

Would you consider replacing the squashing implementation by a "verbatim" one?

Namely:

* copy all ruby code in each `up` or `change` method. Almost no parsing needed
* Paste it, in order, in the resulting `init_schema.rb` migration

Cheers - Victor

**Comment by jalkoby** [comment]
Hi and sorry for delay in the response. The idea of the gem is creating database schema dump in rails migration format. If you put some data in your migrations better to think about seed.rb or rake tasks(at the end the gem ask to safe database which will be useful). If your application has a different db scheme according to an environment - better to handle it on your own rather using this gem(it's not a common case for rails development).
