### ISSUE TITLE
Trailing whitespace, unnecessary empty line, double-quoted strings in generated migration file

### ISSUE THREAD

**Issue by krowpu** [jalkoby/squasher#32]
Trailing whitespaces are highlighted with red at the screenshot. Trailing whitespace should not present in code. Also unnecessary empty line (diff line 3 at the screenshot, after `def up`) should not be generated. Also it's better to use single-quoted strings. It's not too pedantic. RuboCop traits these cases as errors. It would be cool not force user to fix this manually.

![screenshot from 2017-03-08 09 38 55](https://cloud.githubusercontent.com/assets/16467161/23690401/94b7bada-03eb-11e7-90bc-7b71a41dbe91.png)

**Comment by jalkoby** [comment]
yeah, it would be nice to remove them

**Comment by jalkoby** [comment]
version 0.2.2 has it
