### ISSUE TITLE
Squasher cuts head off view creation - LECT instead of SELECT

### ISSUE THREAD

**Issue by adfineberg** [jalkoby/squasher#34]
Ran on Rails 4.2.6.
This happened on all our views, here is an example (removed some columns):
```
create_view "versions", <<-'END_VIEW_VERSIONS', :force => true
    LECT versions_master.id,
      versions_master.item_type,
      versions_master.created_at
     FROM versions_master
    END_VIEW_VERSIONS
```

The view was created running this sql:
`CREATE OR REPLACE VIEW versions AS SELECT * FROM versions_master;`

**Comment by jalkoby** [comment]
Hi, looks like I need to rework indentation processing. Will try to publish fix in a couple of days

**Comment by adfineberg** [comment]
Yeah, looks like the schema.rb sticks their raw SQL from the first character. 
I guess replacing render.rb:27 with something in the lines of:
`yield (line[0..1].to_s == '  ') ? line[2...-1].to_s : line.to_s`
should do the trick.

**Comment by jalkoby** [comment]
the bug is fixed. Enjoy 0.3.1
