### ISSUE TITLE
Rails 5 changes 

### ISSUE THREAD

**Issue by duskhacker** [jalkoby/squasher#35]
I had to edit:

`lib/squasher/templates/squasher_clean.rb.erb`
`lib/squasher/templates/init_schema.rb.erb` 

to add the `[5.1]` to the end of `ActiveRecord::Migration` as is now required. 

Also, the program will bomb if: 

`config.active_record.schema_format = :sql` is set. Might want to add that to the documentation.

**Comment by jalkoby** [comment]
Hi. thanks for the feedback about rails 5.1 features, I'll try to add the support soon. About `sql` config - have you read https://github.com/jalkoby/squasher#requirements ?

**Comment by jalkoby** [comment]
Support of rails 5 migration was added in 0.4.0 - enjoy
