### ISSUE TITLE
Squashed data into seeds.rb

### ISSUE THREAD

**Issue by adfineberg** [jalkoby/squasher#36]
Hey,
I wrote a script that appends all the data from the squasher DB into seeds.rb.
Is this a feature that would interest you?

**Comment by jalkoby** [comment]
yeah, I guess it's a good idea

**Comment by brandondrew** [comment]
I was just about to suggest something similar... (actually, I was going to suggest _not deleting_ the migrations that added data, but this is probably a better solution to the same problem)... any reason this hasn't been added?

**Comment by jalkoby** [comment]
@brandondrew it's not a case, squasher doesn't work with migration files directly

**Comment by adfineberg** [comment]
Sure, sorry I couldn't get to writing something more generic:
https://gist.github.com/adfineberg/5b6a46cc044702c7a81bb9ef788e179f
