### ISSUE TITLE
Output table creation includes force: :cascade option

### ISSUE THREAD

**Issue by sgringwe** [jalkoby/squasher#37]
The outputted init migration includes `force: :cascade` option for all `create_table` calls. This is likely unwanted, since that option deletes it and all referenced tables if it already exists which would of course be quite catastrophic if accidentally run in production.

**Comment by jalkoby** [comment]
Hi - thanks for your feedback, but it's not a "should be added" feature. So if it's critical for you - feel free to make a PR. Until that I'm closing the issue
