### ISSUE TITLE
How to deal with postgresql enums ?

### ISSUE THREAD

**Issue by zedalaye** [jalkoby/squasher#38]
Looks like squasher don't know how to serialize postgresql enums : 

    # Could not dump table "orders" because of following StandardError
    #   Unknown type 'order_status' for column 'status'

They are now supported by ActiveRecord : http://edgeguides.rubyonrails.org/active_record_postgresql.html#enumerated-types

In the migrations I'm trying to squash, enums have been created using SchemaPlus using create_enum (https://github.com/SchemaPlus/schema_plus_enums)

Should I reincorporate missing enums/tables in the resulting migration by hand ?

**Comment by jalkoby** [comment]
Hi, squasher works only with ActiveRecord types. As I see you have sql schema in your app - for the moment it's not supported
