### ISSUE TITLE
Squasher couldn't load `database.yml`, but it's there!

### ISSUE THREAD

**Issue by jmuheim** [jalkoby/squasher#47]
```
$ squasher 2015
Squasher couldn't load `database.yml`. Please, make sure that it's present and doesn't include any ruby code.
$ ls config
... database.yml ...
```

**Comment by jalkoby** [comment]
what's inside the database file? Maybe there is some code which is not interpreted by squasher

**Comment by jalkoby** [comment]
any news through? feel free to reopen the issue with a new details

**Comment by lukelex** [comment]
Why shouldn't it have ruby code though?

**Comment by jalkoby** [comment]
@lukelex  you can use any valid ruby code inside database.yml, but squasher doesn't load rails env, so if there is any references to your app code - it just will fail
