### ISSUE TITLE
Specify Rails release for migrations

### ISSUE THREAD

**Issue by davidwessman** [jalkoby/squasher#50]
The generated migrations does not include a Rails version and generates the error:
`Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for`.

**Edit**
There should be support for it since [this commit](https://github.com/jalkoby/squasher/commit/724602ebf291ae2f8bdfe86149777d878eef565b).
But the generated file I got did not have any version defined.

Using Rails 5.2.0.rc1

**Comment by jalkoby** [comment]
Have you run the command like this "squasher 2017 -m 5.0" ?

**Comment by davidwessman** [comment]
Aha! My fault, did not see it in the readme.
Thanks :)
