### ISSUE TITLE
Squahser does not work when the database was previously setup with db:schema:load

### ISSUE THREAD

**Issue by luizkowalski** [jalkoby/squasher#51]
In the past, we had a folder with a lot of migrations and at some point, we deleted all of them and decided to go with `db:schema:load` and then use `db:migrate` from that point in time on.

Now when I try to use squasher, I get `PG::UndefinedTable: ERROR:  relation "table_name" does not exist` because it is supposed to be loaded via `db:schema:load`

**Comment by jalkoby** [comment]
Hi. squasher relays on working database migrations. Please fix a fresh install (run your migration on empty database) and then use squasher
