### ISSUE TITLE
Prevent "force" table creation as it leads to dangerous situations

### ISSUE THREAD

**Issue by afunction** [jalkoby/squasher#56]
My production have not migrate to newest version, and I use squasher compression mgiration file, then the  compressed migration force create table ....

then I spent whole day to save my production site.

you should write warning message on README

**Comment by jalkoby** [comment]
Sorry to hear that. could you bring a more details what has happened?

**Comment by BrianVegeta** [comment]
I'm his colleague,

Your gem will use latest migration timestamp to generator a new compress migration for init.
for example:

```
production latest migration: 20181010_xxxxx.rb
local latest migration: 20181106_xxxx.rb 
```
And I run squasher to compress migration to `20181106` that include not release to production migration files. 

Then new not release migration enforce create table (drop then create), All my production data (4.xGB) dispear .....

I think you should not use enforce create mode, and write warning on README.

**Comment by jalkoby** [comment]
ok, that's make sense. basically we need to disable "force: true" which will prevent such situations

**Comment by jalkoby** [comment]
the version 0.6.2 doesn't have it - any sorry to here such use-case
