### ISSUE TITLE
When the migrations don't work - Issue #51 rethought

### ISSUE THREAD

**Issue by MadBomber** [jalkoby/squasher#59]
I've got an old legacy system with ~1000 migrations that went from rails 3 to 4 and now we're looking at an upgrade to 5.  Somewhere along the line some mods were made to the database not though a migration and/or migrations were made and later lost out of the git repo.

We typically build new databases by duplication existing datavase and/or using db:schema:load.

This is basically the same situation as Issue #51 

What I am thinking is that we can identify a point in time at which the db/schema.rb file is valid.  Whe then use it to build a base initialization migration, deleting all prior migrations from that date backwards.

From that point forward `squasher` should be able to work as expected.

Any thoughts on that approach?

**Comment by jalkoby** [comment]
don't know - error log probably helps
