### ISSUE TITLE
ActiveRecord::AdapterNotSpecified: database configuration does not specify adapter (Rails 6)

### ISSUE THREAD

**Issue by aurels** [jalkoby/squasher#60]
Hi,

When running it, I get : 

    Squasher is creating a tmp database
    rake aborted!
    ActiveRecord::AdapterNotSpecified: database configuration does not specify adapter

We are on Rails 6.0.2.2 and we use the "multi database" built in option of Rails, I guest it's related ?

The `database.yml` looks like : 

    default: &DEFAULT
      primary:
        adapter: "postgresql"
        encoding: "unicode"
        host: "<%= ENV["PG_HOST"] %>"
        port: "<%= ENV["PG_PORT"] %>"
        database: "<%= ENV["PG_DATABASE"] %>"
        username: "<%= ENV["PG_USERNAME"] %>"
        password: "<%= ENV["PG_PASSWORD"] %>"
        pool: 200
    
      other:
        ...
    
    development:
      <<: *DEFAULT
      primary:
        adapter: "postgresql"
        encoding: "unicode"
        host: "<%= ENV["PG_HOST"] %>"
        port: "<%= ENV["PG_PORT"] %>"
        database: "<%= ENV["PG_DATABASE"] %>"
        username: "<%= ENV["PG_USERNAME"] %>"
        password: "<%= ENV["PG_PASSWORD"] %>"
        pool: 200
        prepared_statements: false

Thanks !

**Comment by jalkoby** [comment]
will take a look soon

**Comment by akashDeep07** [comment]
Hello I'm working on rails 4.0.12 and want to connect 2 db (mysql and postgresql) with my current application. Currently mysql is already connected with it and when i tried to connect postgresql it raise an error.

 "database configuration does not specify adapter (ActiveRecord::AdapterNotSpecified)"
 
 I'm using this https://medium.com/@shilpikayal/dual-database-connection-in-rails-76ca42e276a7 as a reference. 
 Any kind of help will be appreciable, Thanks.

**Comment by akashDeep07** [comment]
> Hi,
> 
> When running it, I get :
> 
> ```
> Squasher is creating a tmp database
> rake aborted!
> ActiveRecord::AdapterNotSpecified: database configuration does not specify adapter
> ```
> 
> We are on Rails 6.0.2.2 and we use the "multi database" built in option of Rails, I guest it's related ?
> 
> The `database.yml` looks like :
> 
> ```
> default: &DEFAULT
>   primary:
>     adapter: "postgresql"
>     encoding: "unicode"
>     host: "<%= ENV["PG_HOST"] %>"
>     port: "<%= ENV["PG_PORT"] %>"
>     database: "<%= ENV["PG_DATABASE"] %>"
>     username: "<%= ENV["PG_USERNAME"] %>"
>     password: "<%= ENV["PG_PASSWORD"] %>"
>     pool: 200
> 
>   other:
>     ...
> 
> development:
>   <<: *DEFAULT
>   primary:
>     adapter: "postgresql"
>     encoding: "unicode"
>     host: "<%= ENV["PG_HOST"] %>"
>     port: "<%= ENV["PG_PORT"] %>"
>     database: "<%= ENV["PG_DATABASE"] %>"
>     username: "<%= ENV["PG_USERNAME"] %>"
>     password: "<%= ENV["PG_PASSWORD"] %>"
>     pool: 200
>     prepared_statements: false
> ```
> 
> Thanks !

Hello I'm working on rails 4.0.12 and want to connect 2 db (mysql and postgresql) with my current application. Currently mysql is already connected with it and when i tried to connect postgresql it raise an error.

"database configuration does not specify adapter (ActiveRecord::AdapterNotSpecified)"

I'm using this https://medium.com/@shilpikayal/dual-database-connection-in-rails-76ca42e276a7 as a reference.
Any kind of help will be appreciable, Thanks.

**Comment by aurels** [comment]
Is this fixed ? Thanks.

**Comment by pioz** [comment]
I'm trying to run Squasher v0.7.2 on a Rails 5.2.8.1 project but I get this error message:

```
Squasher is creating a tmp database
rake aborted!
ActiveRecord::AdapterNotSpecified: 'development' database is not configured. Available: ["database"]
```

Any suggestions?

**Comment by joshRpowell** [comment]
Still seeing this issue in Rails 7.2. 

I was able to get this to work by commenting out the `primary` key and all of the non-primary dbs. 

when the temporary `database.yml` is created:

```yml
development:
  primary:
    adapter: postgresql
    encoding: utf8
    pool: 5
    collation: C
    ctype: C
    template: template0
    database: development
  database: squasher
    adapter: # this is missing
```
