### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by m5rk** [jalkoby/squasher#64]
Conceptually, squashing works like this:

1. Delete all migrations.
2. Create a new migration, with a version matching the one in db/schema.rb.
3. Copy the contents of db/schema.db into the new migration's change method.

What is the approach taken by this gem?

**Comment by tannerhallman** [comment]
I would recommend you test the gem yourself. From my initial tests, I can determine that it:

1. Deletes migrations prior to a specified point
2. Creates a new migration (`InitSchema`) that would setup the database according to schema at the specified point in time.
