### ISSUE TITLE
Missing migrations which uses "execute" method

### ISSUE THREAD

**Issue by vikramjagirdar** [jalkoby/squasher#9]
We have some migrations which uses database commands through execute method and that is not reflected in squash file genereated. Is there any work around to fix this?

**Comment by stmcintyre** [comment]
@jalkoby - thanks for your efforts with this gem, it works really well with standard Rails migrations.  Unfortunately we have some execute SQL migrations peppered throughout several apps to create DB views.  These can't be moved into the seed file as suggested above.  Any ideas on how we could handle DB view creation outside migrations, that would allow us to use Squasher?

**Comment by jalkoby** [comment]
You can leave the temporary database, dump views into sql and execute sql in the end of the initial migration
